//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_DAMAU.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.HOADONCHITIETs = new HashSet<HOADONCHITIET>();
        }
    
        public string MA_SACH { get; set; }
        public string TEN_SACH { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public string MA_NXB { get; set; }
        public string MA_THELOAI { get; set; }
        public string MA_NHACUNGCAP { get; set; }
        public string MA_TACGIA { get; set; }
        public byte[] ANH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONCHITIET> HOADONCHITIETs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual TACGIA TACGIA { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
